# <center> Preparation of the data, turn all features numerical </center>

## Load data

In [1]:
from pandas import read_csv
import pandas as pd
train_full = read_csv('../HousePrices/trainfull.csv', index_col=0)
test = read_csv('../HousePrices/test.csv', index_col=0)

## Select only the categorical features

In [2]:
train_full_object = train_full.select_dtypes(include='object')
train_full_object = train_full_object.fillna('None')
test_object = test.select_dtypes(include='object')
test_object = test_object.fillna('None')

In [3]:
# pip install category_encoders

In [4]:
import category_encoders as ce
from sklearn.preprocessing import OneHotEncoder
ohe = ce.OneHotEncoder(handle_unknown='ignore', use_cat_names=True)

trainfull_ohe = ohe.fit_transform(train_full_object)
trainfull_ohe.head()

,MSZoning_RL,MSZoning_RM,MSZoning_C (all),MSZoning_FV,MSZoning_RH,Street_Pave,Street_Grvl,Alley_None,Alley_Grvl,Alley_Pave,...,SaleType_CWD,SaleType_ConLw,SaleType_Con,SaleType_Oth,SaleCondition_Normal,SaleCondition_Abnorml,SaleCondition_Partial,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family
Id,,,,,,,,,,,,,,,,,,,,,
1,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
3,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
4,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
5,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0

In [5]:
test_ohe = ohe.transform(test_object)
test_ohe.head()

,MSZoning_RL,MSZoning_RM,MSZoning_C (all),MSZoning_FV,MSZoning_RH,Street_Pave,Street_Grvl,Alley_None,Alley_Grvl,Alley_Pave,...,SaleType_CWD,SaleType_ConLw,SaleType_Con,SaleType_Oth,SaleCondition_Normal,SaleCondition_Abnorml,SaleCondition_Partial,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family
Id,,,,,,,,,,,,,,,,,,,,,
1461,0.0,0.0,0.0,0.0,1.0,1,0,1,0,0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1462,1.0,0.0,0.0,0.0,0.0,1,0,1,0,0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1463,1.0,0.0,0.0,0.0,0.0,1,0,1,0,0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1464,1.0,0.0,0.0,0.0,0.0,1,0,1,0,0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1465,1.0,0.0,0.0,0.0,0.0,1,0,1,0,0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0

## Same treatment for the numerical features

In [7]:
train_full_number = train_full.select_dtypes(exclude='object')
train_full_number = train_full_number.fillna(0)
test_number = test.select_dtypes(exclude='object')
test_number = test_number.fillna(0)

Concatener the numerical and categorical features into one dataframe trainfull

In [10]:
import pandas as pd
trainfull = pd.concat([train_full_number, trainfull_ohe], axis=1)
trainfull.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_CWD,SaleType_ConLw,SaleType_Con,SaleType_Oth,SaleCondition_Normal,SaleCondition_Abnorml,SaleCondition_Partial,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,0,1,0,0,0,0,0
2,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,0,1,0,0,0,0,0
3,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,0,1,0,0,0,0,0
4,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,0,0,1,0,0,0,0
5,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,0,1,0,0,0,0,0

In [11]:
test = pd.concat([test_number, test_ohe], axis=1)
test.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_CWD,SaleType_ConLw,SaleType_Con,SaleType_Oth,SaleCondition_Normal,SaleCondition_Abnorml,SaleCondition_Partial,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0

## Split data

Let's do 80-20%:

In [12]:
from numpy import random
SEED = 42
random.seed(SEED)

In [13]:
from sklearn.model_selection import train_test_split
VAL_SIZE = 0.2
train, val = train_test_split(trainfull, test_size=VAL_SIZE)

In [14]:
print("Train full shape: " + str(trainfull.shape))
print("Train shape: " + str(train.shape))
print("Val shape: " + str(val.shape))
print("Test shape" + str(test.shape))

Train full shape: (1460, 304)
Train shape: (1168, 304)
Val shape: (292, 304)
Test shape(1459, 303)

## Save data

In [15]:
trainfull.to_csv("trainfull_ohe.csv")
test.to_csv("test_ohe.csv")
train.to_csv("train_ohe.csv")
val.to_csv("val_ohe.csv")